CREATE DATABASE ServiceBusEmulator;
GO

USE ServiceBusEmulator;
GO

CREATE TABLE SentMessages (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    QueueName NVARCHAR(200),
    MessageBody NVARCHAR(MAX),
    SentAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE ReceivedMessages (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    QueueName NVARCHAR(200),
    MessageBody NVARCHAR(MAX),
    ReceivedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);
