import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type MessagingResourceDocument = MessagingResource & Document;

export enum Provider {
  AWS = 'AWS',
  AZURE = 'Azure',
}

export enum ResourceType {
  QUEUE = 'Queue',
  TOPIC = 'Topic',
}

@Schema({ collection: 'MessagingResources', timestamps: true })
export class MessagingResource {
  // _id is automatically generated by Mongoose

  @Prop({ required: true, unique: true, index: true })
  id!: string;

  @Prop({ required: true })
  name!: string;

  @Prop({ required: true, enum: Provider })
  provider!: Provider;

  @Prop({ required: true, enum: ResourceType })
  type!: ResourceType;

  @Prop({ required: true })
  region!: string;

  @Prop({
    required: true,
    enum: ['active', 'inactive'],
    default: 'active',
  })
  status!: 'active' | 'inactive';
}

export const MessagingResourceSchema =
  SchemaFactory.createForClass(MessagingResource);
