import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type TrackingMessageDocument = TrackingMessage & Document;

export const trackingStatuses = ['sent', 'processing', 'received'] as const;
export type TrackingStatus = (typeof trackingStatuses)[number];

export const messageDispositions = [
  'complete',
  'abandon',
  'deadletter',
  'defer',
] as const;
export type MessageDisposition = (typeof messageDispositions)[number];

export const emulatorTypes = ['sqs', 'azure-service-bus'] as const;
export type EmulatorType = (typeof emulatorTypes)[number];

@Schema({ collection: 'Messages', timestamps: true })
export class TrackingMessage {
  // _id is automatically generated by Mongoose, no need to define it explicitly
  
  @Prop({ required: true })
  messageId?: string;

  @Prop({ required: true })
  body?: string;

  @Prop({ required: true })
  sentBy?: string;

  @Prop({ required: true })
  sentAt?: Date;

  @Prop()
  queue?: string;

  @Prop()
  receivedBy?: string;

  @Prop()
  receivedAt?: Date;

  @Prop({ required: true, enum: trackingStatuses, default: 'processing' })
  status?: TrackingStatus;

  @Prop({ enum: messageDispositions })
  disposition?: MessageDisposition;

  @Prop({ required: true, enum: emulatorTypes, default: 'azure-service-bus' })
  emulatorType?: EmulatorType;
}


export const TrackingMessageSchema = SchemaFactory.createForClass(TrackingMessage);

TrackingMessageSchema.index(
  { emulatorType: 1, messageId: 1 },
  { unique: true },
);
