import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type TrackingMessageDocument = TrackingMessage & Document;

@Schema({ collection: 'Messages', timestamps: true })
export class TrackingMessage {
  // _id is automatically generated by Mongoose, no need to define it explicitly
  
  @Prop({ required: true })
  messageId?: string;

  @Prop({ required: true })
  body?: string;

  @Prop({ required: true })
  sentBy?: string;

  @Prop({ required: true })
  sentAt?: Date;

  @Prop()
  queue?: string;

  @Prop()
  receivedBy?: string;

  @Prop()
  receivedAt?: Date;

  @Prop({ required: true, enum: ['sent', 'processing', 'received'], default: 'processing' })
  status?: string;

  @Prop({ enum: ['complete', 'abandon', 'deadletter', 'defer'] })
  disposition?: string;

  @Prop({ required: true, enum: ['sqs', 'azure-service-bus'], default: 'azure-service-bus' })
  emulatorType?: string;
}


export const TrackingMessageSchema = SchemaFactory.createForClass(TrackingMessage);
