import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type TrackingMessageDocument = TrackingMessage & Document;

@Schema({ collection: 'Messages', timestamps: true })
export class TrackingMessage {
  // _id is automatically generated by Mongoose, no need to define it explicitly
  
  @Prop({ required: true })
  messageId?: string;

  @Prop({ required: true })
  body?: string;

  @Prop({ required: true })
  sentBy?: string;

  @Prop({ required: true })
  sentAt?: Date;

  @Prop()
  queue?: string;

  @Prop()
  receivedBy?: string;

  @Prop()
  receivedAt?: Date;

  @Prop({ required: true, enum: ['sent', 'received'], default: 'sent' })
  status?: string;
}


export const TrackingMessageSchema = SchemaFactory.createForClass(TrackingMessage);
